version: "1.0"

services:
  app:
    container_name: el-rastro-backend
    image: el-rastro-backend
    build:
      context: .
      target: development
    volumes:
      - ./elRastro-backend:/elRastro-backend
    ports:
      - 5001:5001